id: PB861324C
initial_creation_type: input
source_metadata:
  title: Kurukullā Series
  language: bo
  description: 'Texts related to Kurukullā (rig byed ma)—also known to Tibetans as
    Kurukulle—a deity of the Lotus family associated with the activity of magnetization
    or enchantment and one of the twenty-one Tārā emanations:'
  volume:
    dc5e856daf29427f93032fed62b1f573:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    53be0d36e6d34c0987dc58edf255b2dc:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Sādhanas
    2f54055168ee4ca6bb5996b081339253:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    a5ab9c4f6f3a4e1c819907d03650ee16:
      title: Short Sang Offering to Kurukullā
      parent: Sang Offering
    6bbc416329074b85b6a831cd9923cb04:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Sang Offering
    0d5a884ecd59471ea99205136bf789c0:
      title: Short Torma Offering to Kurukullā
      parent: Torma Offering
    a24bb1e6749d4975b2b928ce4d359523:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Tsok
created_at: '2022-03-01T04:06:17.443193'
last_modified_at: '2022-03-01T04:06:17.443196'
statistics:
  total_words: 2823
  total_non_words: 330
quality:
  non_words_ratio: 0.12
